In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= sns.load_dataset('iris')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df = df[['sepal_length','petal_length','species']]

In [5]:
df.head()

sepal_length  petal_length species
0           5.1           1.4  setosa
1           4.9           1.4  setosa
2           4.7           1.3  setosa
3           4.6           1.5  setosa
4           5.0           1.4  setosa

In [6]:
encoder = LabelEncoder()

In [7]:
df['species'] = encoder.fit_transform(df['species'])

In [8]:
df.head()

sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [9]:
df.species.value_counts()

0    50
1    50
2    50
Name: species, dtype: int64

In [11]:
X = df.iloc[:,0:2]

In [12]:
X.head()

sepal_length  petal_length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

In [13]:
y = df.iloc[:,-1]

In [15]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int32

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [17]:
clf = LogisticRegression(multi_class='multinomial')

In [18]:
clf.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial')

In [19]:
y_pred= clf.predict(X_test)

In [20]:
print(accuracy_score(y_test,y_pred))

0.9666666666666667


In [21]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  1],
       [ 0,  0,  8]], dtype=int64)

In [23]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

0  1  2
0  14  0  0
1   0  7  1
2   0  0  8

In [37]:
a = np.array([[1.5,2.7]])

In [38]:
clf.predict_proba(a)

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[8.84025743e-01, 1.15535234e-01, 4.39022373e-04]])

In [39]:
clf.predict(a)

c:\users\dell\appdata\local\programs\python\python39\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])